services:
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlflow
    ports:
      - "5000:5000"
    volumes:
      - mldata:/ml/
    depends_on:
      - postgres
    command: >
      mlflow server 
      --host=0.0.0.0 
      --backend-store-uri postgresql://mlflow:mlflow@postgres/mlflow_db
      --artifacts-destination file:///ml/mlartifacts
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  mldata:

  pgdata: