channels:
- conda-forge
dependencies:
- python=3.11.9
- pip<=25.1.1
- pip:
  - mlflow==2.22.0
  - cffi==1.16.0
  - cloudpickle==2.2.1
  - defusedxml==0.7.1
  - graphviz==0.20.1
  - lightgbm==4.3.0
  - matplotlib==3.8.0
  - numpy==1.26.4
  - pandas==2.2.3
  - psutil==5.9.5
  - pyarrow==15.0.2
  - scikit-learn==1.3.2
  - scipy==1.15.3
name: mlflow-env
