channels:
- conda-forge
dependencies:
- python=3.11.9
- pip<=25.1.1
- pip:
  - mlflow==2.22.0
  - cloudpickle==2.2.1
  - numpy==1.26.4
  - pandas==2.2.3
  - psutil==5.9.5
  - scikit-learn==1.3.2
  - scipy==1.15.3
  - xgboost==2.0.3
name: mlflow-env
