version: 1
disable_existing_loggers: false

formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

# You must have at least an empty 'loggers' mapping:
loggers: {}

# Finally, define the root logger
root:
  handlers: [console]
  level: INFO